import type { Category, Template } from "@/types";

export const mockCategories: Category[] = [
  {
    id: "cat-1",
    name: "Cadeau maîtresse",
    name_en: "Teacher gift",
    slug: "cadeau-maitresse",
    description: "Pour remercier avec amour",
    icon: "Gift",
    cover_image_url: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&q=80",
    display_order: 1,
  },
  {
    id: "cat-2",
    name: "Fête des mères",
    name_en: "Mother's Day",
    slug: "fete-des-meres",
    description: "Des créations qui viennent du cœur",
    icon: "Flower2",
    cover_image_url: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=600&q=80",
    display_order: 2,
  },
  {
    id: "cat-3",
    name: "Mariage",
    name_en: "Wedding",
    slug: "mariage",
    description: "Le plus beau jour en beauté",
    icon: "Heart",
    cover_image_url: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80",
    display_order: 3,
  },
  {
    id: "cat-4",
    name: "Naissance",
    name_en: "Birth",
    slug: "naissance",
    description: "Accueillir le nouveau-né avec douceur",
    icon: "Baby",
    cover_image_url: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80",
    display_order: 4,
  },
  {
    id: "cat-5",
    name: "Noël",
    name_en: "Christmas",
    slug: "noel",
    description: "Magie et chaleur pour les fêtes",
    icon: "Star",
    cover_image_url: "https://images.unsplash.com/photo-1482833973580-6f833f95b807?w=600&q=80",
    display_order: 5,
  },
  {
    id: "cat-6",
    name: "Décoration",
    name_en: "Home decor",
    slug: "decoration",
    description: "Votre intérieur, votre signature",
    icon: "Home",
    cover_image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    display_order: 6,
  },
];

export const mockTemplates: Template[] = [
  {
    id: "tpl-1",
    title: "Tableau prénom bohème",
    title_en: "Boho name sign",
    description: "Un tableau décoratif avec prénom en calligraphie entouré de feuillages bohème",
    description_en: "A decorative name sign with calligraphy surrounded by boho foliage",
    image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    category_id: "cat-6",
    tags: ["bohème", "prénom", "calligraphie", "déco"],
    style: "bohème",
    prompt_base: "Create a boho style name sign with calligraphy, delicate botanical elements, warm earth tones",
    is_featured: true,
    popularity: 892,
  },
  {
    id: "tpl-2",
    title: "Cadeau maîtresse fleurs aquarelle",
    title_en: "Teacher gift watercolor flowers",
    description: "Un cadeau personnalisé pour la maîtresse avec fleurs aquarelle et message",
    description_en: "A personalized teacher gift with watercolor flowers and message",
    image_url: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&q=80",
    category_id: "cat-1",
    tags: ["maîtresse", "aquarelle", "fleurs", "cadeau"],
    style: "aquarelle",
    prompt_base: "Create a sweet teacher gift design with watercolor flowers, soft pastels, handwritten style message",
    is_featured: true,
    popularity: 756,
  },
  {
    id: "tpl-3",
    title: "Faire-part mariage champêtre",
    title_en: "Rustic wedding invitation",
    description: "Faire-part romantique et champêtre avec fleurs sauvages et typographie élégante",
    description_en: "Romantic rustic wedding invitation with wildflowers and elegant typography",
    image_url: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80",
    category_id: "cat-3",
    tags: ["mariage", "champêtre", "fleurs", "faire-part"],
    style: "champêtre",
    prompt_base: "Create an elegant rustic wedding invitation with wildflowers, soft watercolor, serif typography",
    is_featured: true,
    popularity: 1043,
  },
  {
    id: "tpl-4",
    title: "Affiche naissance minimaliste",
    title_en: "Minimalist birth poster",
    description: "Affiche de naissance avec prénom, date et poids dans un style épuré et moderne",
    description_en: "Birth poster with name, date and weight in a clean modern style",
    image_url: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80",
    category_id: "cat-4",
    tags: ["naissance", "affiche", "minimaliste", "bébé"],
    style: "minimaliste",
    prompt_base: "Create a minimalist birth announcement poster with baby name, birthdate, weight, soft colors",
    is_featured: false,
    popularity: 634,
  },
  {
    id: "tpl-5",
    title: "Étiquette cadeau Noël vintage",
    title_en: "Vintage Christmas gift tag",
    description: "Étiquettes cadeaux au style vintage avec illustrations de Noël et personnalisation",
    description_en: "Vintage style Christmas gift tags with illustrations and personalization",
    image_url: "https://images.unsplash.com/photo-1482833973580-6f833f95b807?w=600&q=80",
    category_id: "cat-5",
    tags: ["Noël", "étiquette", "vintage", "cadeau"],
    style: "vintage",
    prompt_base: "Create vintage style Christmas gift tags with holly, ribbon, warm red and gold tones",
    is_featured: false,
    popularity: 512,
  },
  {
    id: "tpl-6",
    title: "Carte fête des mères fleurie",
    title_en: "Floral Mother's Day card",
    description: "Carte élégante pour la fête des mères avec bouquet fleuri et message personnalisé",
    description_en: "Elegant Mother's Day card with floral bouquet and personalized message",
    image_url: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=600&q=80",
    category_id: "cat-2",
    tags: ["fête des mères", "fleurs", "carte", "élégant"],
    style: "élégant",
    prompt_base: "Create an elegant Mother's Day card with beautiful floral arrangement, pastel colors, heartfelt message area",
    is_featured: true,
    popularity: 876,
  },
  {
    id: "tpl-7",
    title: "Plaque de porte chambre enfant",
    title_en: "Children's room door sign",
    description: "Plaque de porte personnalisée pour chambre d'enfant avec prénom et illustration",
    description_en: "Personalized door sign for children's room with name and illustration",
    image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    category_id: "cat-6",
    tags: ["enfant", "chambre", "plaque", "prénom"],
    style: "enfantin",
    prompt_base: "Create a cute children's room door sign with colorful illustration, playful typography",
    is_featured: false,
    popularity: 423,
  },
  {
    id: "tpl-8",
    title: "Invitation anniversaire floral",
    title_en: "Floral birthday invitation",
    description: "Invitation d'anniversaire élégante avec décor floral et typographie fine",
    description_en: "Elegant birthday invitation with floral decor and fine typography",
    image_url: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&q=80",
    category_id: "cat-6",
    tags: ["anniversaire", "invitation", "floral", "élégant"],
    style: "élégant",
    prompt_base: "Create an elegant birthday invitation with floral elements, gold accents, sophisticated typography",
    is_featured: false,
    popularity: 389,
  },
];
